# Generated by Django 5.2.5 on 2026-04-06 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('class_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muster_sessions', to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='MusterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('roll_no', models.CharField(max_length=50)),
                ('usage_price', models.DecimalField(decimal_places=2, default=0, help_text='Usage cost per entry', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muster_entries', to='labs.pc')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='muster.mustersession')),
            ],
            options={
                'ordering': ['sr_no'],
                'unique_together': {('session', 'sr_no')},
            },
        ),
    ]
