# Generated by Django 5.2.5 on 2026-03-30 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterentry',
            name='usage_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usage cost per entry', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
