# Generated by Django 5.2.5 on 2026-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='manual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional manual cost assigned to the lab', max_digits=12),
        ),
    ]
