# Generated by Django 5.2.5 on 2026-03-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_maintenancelog_options_alter_pc_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peripheral',
            unique_together=set(),
        ),
    ]
