# Generated by Django 5.2.5 on 2026-03-30 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_maintenancelog_options_alter_pc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CPU unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='labequipment',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per single unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='os',
            name='license_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='OS license cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pc',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base PC cost before components', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peripheral unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
