# Generated by Django 5.2.5 on 2026-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_peripheral_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
    ]
