# Generated by Django 5.2.5 on 2026-04-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_lab_manual_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripheral_devices', to='labs.pc'),
        ),
    ]
