# Generated by Django 5.2.5 on 2026-03-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_maintenancelog_status'),
        ('labs', '0004_cpu_price_labequipment_unit_price_os_license_cost_and_more'),
    ]

    operations = [
    ]
